### ISSUE TITLE
does not give the result

### ISSUE THREAD

**Issue by git-reports** [git-reports/wolfree#12]
Submitter: valerio
limit n to infinity Surd[n,n]+ Divide[ln\(40)Power[n,2]-1\(41),ln n ] does not give the result

**Comment by Lin2Jing4** [comment]
failing test case: `Limit[Surd[n,n],n->∞]`
<details><summary>screenshots comparing the results of Wolfree and Wolfram</summary><br>

![image](https://user-images.githubusercontent.com/35728132/141602370-bed6a0bc-3164-418d-b734-df9be378bf98.png)
</details>

**Comment by Lin2Jing4** [comment]
failing test case: `Limit[Surd[0,x],x->0]`
<details><summary>screenshots comparing the results of Wolfree and Wolfram</summary><br>

![image](https://user-images.githubusercontent.com/35728132/141603022-12d218b3-15ce-4488-86f1-6b96a7900ac7.png)
</details>

**Comment by Lin2Jing4** [comment]
workaround: replace `Surd[X,Y]` with `X^Y^-1`
<details><summary>solution to <code>limit n to infinity Surd[n,n]+ Divide[ln(40)Power[n,2]-1(41),ln n ]</code></summary><br>

![image](https://user-images.githubusercontent.com/35728132/141604300-78373a29-cc12-4184-89e3-425ac6ec00a0.png)
</details>

**Comment by Lin2Jing4** [comment]
workaround: replace `Surd` with `(#^1/#2)&`

reference: https://reference.wolfram.com/language/ref/Function.html.en

<details><summary>solution to <code>limit n to infinity Surd[n,n]+ Divide[ln(40)Power[n,2]-1(41),ln n ]</code></summary><br>

![image](https://user-images.githubusercontent.com/35728132/141609596-0b0eb87c-5a4b-419f-8efa-bb80fbf4f349.png)</details>
